# Generated by Django 5.0.7 on 2024-07-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='report',
            name='entity_type_id',
            field=models.IntegerField(default=1040),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
