# Generated by Django 5.0.7 on 2024-07-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_report_created_at_remove_report_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
